version: 2 

registries:
  prerelease-nuget:
    type: nuget-feed
    url: ${VARS.ACMEPRERELEASENUGETFEED}
    username: "az"
    password: ${SECRETS.TEST_ADO_TOKEN}

  release-nuget:
    type: nuget-feed
    url: ${VARS.ACMERELEASENUGETFEED}
    username: "az"
    password: ${SECRETS.TEST_ADO_TOKEN}

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    registries:
      - prerelease-nuget
      - release-nuget
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 10   
    labels:
      - "dependencies"
      - "nuget"
